alpha: 0.99
aniso_esp: true
batch_size: 8
beta: 100
cutoff: 5.0
cutoff_esp: 500.0
cutoff_lr: 9.0
data_path: data
decay_factor: 0.02
delta_qm: false
delta_qmmm: false
device_name: cuda
dtype: float32
experiment_name: minimal_float32
gamma: 100
learning_rate: 0.0003
max_grad_norm: 1.0
model_architecture: minimal
mol_charge: 1.0
multi_loss: true
n_channels: 32
n_kernels: 8
n_kernels_qmmm: 8
n_steps: 2
node_size: 128
num_epochs: 64
order: 2
random_seed: 130185
scheduler: ExponentialLR
single_system: false
system_name: pyridine_example

